# Generated by Django 2.0b1 on 2017-12-19 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'perfil', 'verbose_name_plural': 'perfiles'},
        ),
    ]
