# Generated by Django 2.0b1 on 2017-12-19 06:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profile', '0002_auto_20171219_0756'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Texto')),
                ('date', models.DateTimeField(auto_now=True, verbose_name='Fecha')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profile.Profile', verbose_name='Perfil')),
            ],
            options={
                'verbose_name': 'mensaje',
                'verbose_name_plural': 'mensajes',
            },
        ),
    ]
