# Generated by Django 2.0.1 on 2018-01-17 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0004_auto_20180117_1925'),
    ]

    operations = [
        migrations.AddField(
            model_name='relation',
            name='date',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha'),
        ),
    ]
